package com.fersaiyan.cyanbridge.localmodels.catalog

data class LocalModelCatalogEntry(
    val id: String,
    val displayName: String,
    val family: String,
    val providerType: String = "local",
    val engine: String = "llama",
    val format: String = "gguf",
    val sourceUrl: String?,
    val sourcePageUrl: String?,
    val expectedFilename: String,
    val sha256: String?,
    val sizeBytes: Long,
    val quantization: String,
    val contextSizeDefault: Int,
    val promptTemplateId: String,
    val minRamGb: Double,
    val minStorageGb: Double,
    val shortDescription: String,
    val tags: List<String>,
    val gatedDownload: Boolean,
    val licenseTermsNote: String,
    val enabled: Boolean,
)

object LocalModelCatalogRepository {
    val curatedModels: List<LocalModelCatalogEntry> = listOf(
        LocalModelCatalogEntry(
            id = "qwen2.5-0.5b-instruct-q4",
            displayName = "Qwen2.5 0.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 420_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 4.0,
            minStorageGb = 1.0,
            shortDescription = "Fast starter model for offline replies and short reasoning.",
            tags = listOf("fast", "offline", "starter"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-3b-instruct-q4",
            displayName = "Qwen2.5 3B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF",
            expectedFilename = "qwen2.5-3b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 1_910_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 8.0,
            minStorageGb = 3.0,
            shortDescription = "Stronger Qwen model for better response quality on newer phones.",
            tags = listOf("balanced", "quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "gemma3-1b-it-int4-litert",
            displayName = "Gemma 3 1B IT (LiteRT INT4)",
            family = "gemma",
            engine = "litert",
            format = "litertlm",
            sourceUrl = "https://huggingface.co/litert-community/Gemma3-1B-IT/resolve/main/gemma3-1b-it-int4.litertlm",
            sourcePageUrl = "https://huggingface.co/litert-community/Gemma3-1B-IT",
            expectedFilename = "gemma3-1b-it-int4.litertlm",
            sha256 = null,
            sizeBytes = 1_250_000_000L,
            quantization = "INT4",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 6.0,
            minStorageGb = 2.5,
            shortDescription = "Google LiteRT package for Gemma 3 1B with good quality/speed balance.",
            tags = listOf("litert", "gemma", "balanced", "offline"),
            gatedDownload = true,
            licenseTermsNote = "Requires Gemma license acceptance on Hugging Face. Add token in this screen.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "gemma3n-e4b-it-int4-litert",
            displayName = "Gemma 3n E4B IT (LiteRT INT4)",
            family = "gemma",
            engine = "litert",
            format = "litertlm",
            sourceUrl = "https://huggingface.co/google/gemma-3n-E4B-it-litert-lm/resolve/main/gemma-3n-E4B-it-int4.litertlm",
            sourcePageUrl = "https://huggingface.co/google/gemma-3n-E4B-it-litert-lm",
            expectedFilename = "gemma-3n-E4B-it-int4.litertlm",
            sha256 = null,
            sizeBytes = 3_400_000_000L,
            quantization = "INT4",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 10.0,
            minStorageGb = 5.0,
            shortDescription = "Large LiteRT Gemma model for highest quality on flagship devices (recommended over web.task variants).",
            tags = listOf("litert", "gemma", "quality", "offline"),
            gatedDownload = true,
            licenseTermsNote = "Requires Gemma license acceptance on Hugging Face. Add token in this screen.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-1.5b-instruct-q4",
            displayName = "Qwen2.5 1.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 1_210_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 8.0,
            minStorageGb = 2.3,
            shortDescription = "Higher quality small model for stronger phones.",
            tags = listOf("quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
    )

    fun findById(id: String?): LocalModelCatalogEntry? {
        if (id.isNullOrBlank()) return null
        return curatedModels.firstOrNull { it.id == id }
    }
}
