package com.fersaiyan.cyanbridge.localmodels.catalog

data class LocalModelCatalogEntry(
    val id: String,
    val displayName: String,
    val family: String,
    val providerType: String = "local",
    val engine: String = "llama",
    val format: String = "gguf",
    val sourceUrl: String?,
    val sourcePageUrl: String?,
    val expectedFilename: String,
    val sha256: String?,
    val sizeBytes: Long,
    val quantization: String,
    val contextSizeDefault: Int,
    val promptTemplateId: String,
    val minRamGb: Double,
    val minStorageGb: Double,
    val shortDescription: String,
    val tags: List<String>,
    val gatedDownload: Boolean,
    val licenseTermsNote: String,
    val enabled: Boolean,
)

object LocalModelCatalogRepository {
    val curatedModels: List<LocalModelCatalogEntry> = listOf(
        LocalModelCatalogEntry(
            id = "qwen2.5-0.5b-instruct-q4",
            displayName = "Qwen2.5 0.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 420_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 4.0,
            minStorageGb = 1.0,
            shortDescription = "Fast starter model for offline replies and short reasoning.",
            tags = listOf("fast", "offline", "starter"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen3.5-0.8b-q4",
            displayName = "Qwen3.5 0.8B (Q4_K_M)",
            family = "qwen",
            sourceUrl = null,
            sourcePageUrl = "https://huggingface.co/models?search=qwen%203.5%200.8b%20gguf",
            expectedFilename = "qwen3.5-0.8b-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 610_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 5.0,
            minStorageGb = 1.3,
            shortDescription = "Small balanced Qwen variant. Import manually if direct source changes.",
            tags = listOf("fast", "balanced", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "gemma-3-1b-it-q4",
            displayName = "Gemma 3 1B Instruct (Q4)",
            family = "gemma",
            sourceUrl = null,
            sourcePageUrl = "https://huggingface.co/models?search=gemma%203%201b%20gguf",
            expectedFilename = "gemma-3-1b-it-q4.gguf",
            sha256 = null,
            sizeBytes = 1_050_000_000L,
            quantization = "Q4",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 6.0,
            minStorageGb = 2.0,
            shortDescription = "Balanced quality model. Usually gated: import GGUF manually.",
            tags = listOf("balanced", "quality", "offline"),
            gatedDownload = true,
            licenseTermsNote = "Gemma models may require acceptance of Google terms and gated access.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-1.5b-instruct-q4",
            displayName = "Qwen2.5 1.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 1_210_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 8.0,
            minStorageGb = 2.3,
            shortDescription = "Higher quality small model for stronger phones.",
            tags = listOf("quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
    )

    fun findById(id: String?): LocalModelCatalogEntry? {
        if (id.isNullOrBlank()) return null
        return curatedModels.firstOrNull { it.id == id }
    }
}
